<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <!-- REMOVE FSharp.Core NuGet -->
  <ItemGroup>
    <Reference Include="FSharp.Core">
      <HintPath>..\..\packages\FSharp.Core.4.4.1.0\lib\net40\FSharp.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="TrackerOptionsBridge.fs" />
    <Compile Include="..\GlobalAssemblyInfo.fs"/>
  </ItemGroup>

</Project>
